### ISSUE TITLE
auto reboot 

### ISSUE THREAD

**Issue by giovannicandotti** [uniquid/esp32-sdk#2]
Hi, 
it happens that the device reboots every few seconds, please find evidence in the following.
the behaviour is a randomical one: some times it works perfectly for hours.
The full system is composed by  "dev-in-a-box" and "esp32-sdk"
<img width="714" alt="screen shot 2018-07-14 at 17 37 41" src="https://user-images.githubusercontent.com/16572107/42725970-4805e3de-878d-11e8-8299-9803b983f875.png">

**Comment by stefacc** [comment]
Hi giovanni
thank you for your support, we are investigating this
